### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by autofakt** [autofakt/Delicioso-E-Ristorante-Electronic-Menu#18]
We need to prevent the user from going further into the program if there was nothing ordered.
- view order should not work unless something was ordered
- Should not be able to submit order without entering a name
- Should not be able to request check without having submitted order (should probably make it a bool)

**Comment by GhostLee-Kino** [comment]
Agreed.
I also want to add that the payment method needs to be validated. a msg box can let the user know that there was a problem with the information entered and to try again.

**Comment by hopefull-lee** [comment]
i've done part of this...I completed th input validation for the customer name so it won't go to ViewOrder form if theres no name... but it still currently goes to view order form if no food is selected.

**Comment by hopefull-lee** [comment]
Alright, I've written the code to complete the necessary validation for all 3 of these buttons.
